# Nama workflow yang akan muncul di tab Actions
name: 'CI & Discord Notification'

# Kapan workflow ini dijalankan?
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ 'main' ]

# Pekerjaan (job) yang akan dijalankan
jobs:
  # Nama job: build-and-test
  build-and-test:
    # Gunakan runner (mesin virtual) Ubuntu terbaru
    runs-on: ubuntu-latest

    # Langkah-langkah (steps) yang akan dijalankan
    steps:
      # Step 1: Download kode sumber dari repository
      - name: Checkout source code
        uses: actions/checkout@v4

      # --- STEP BARU: INSTALL LLVM ---
      # Step ini akan menginstall LLVM 14 dan Clang 14 yang dibutuhkan oleh inkwell
      - name: Install LLVM
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-14-dev clang-14

      # Step 2: Install Rust toolchain (compiler, cargo, dll)
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          # Tambahkan komponen clippy untuk analisis kode statis
          components: clippy

      # Step 3: Periksa kode (cepat) untuk cari error sintaks
      - name: Run cargo check
        run: cargo check --verbose

      # Step 4: Jalankan semua test yang ada
      - name: Run tests
        run: cargo test --verbose

      # Step 5: Build aplikasi dalam mode release
      - name: Build project
        run: cargo build --release --verbose

      # Step 6: Kirim notifikasi ke Discord
      - name: Notify Discord on success or failure
        # Gunakan 'always()' agar step ini selalu dijalankan,
        # baik build-nya sukses maupun gagal.
        if: always()
        # Gunakan action dari marketplace untuk mempermudah
        uses: sarisia/actions-status-discord@v1
        with:
          # Ambil URL webhook dari secret yang kita buat tadi
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          # Judul notifikasi
          title: "Build Result: ${{ job.status }}"
          # Deskripsi notifikasi, bisa berisi link ke commit
          description: |
            Commit: `${{ github.sha }}`
            Author: ${{ github.actor }}
            Message: ${{ github.event.head_commit.message }}
            [View Workflow Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          # Warna notifikasi (hijau untuk sukses, merah untuk gagal)
          color: ${{ job.status == 'success' && '0x28a745' || '0xdc3545' }}
          # Avatar yang digunakan (logo GitHub)
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
